application: thumbnail-service
version: 3
runtime: python
api_version: 1
derived_file_type:
- python_precompiled

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (manage.py)|
 (gdata/.*)|
 (resources/.*)|
 (docutils/.*)|
 (README.*)|
 (CHANGELOG)|
 (Makefile)|
 (bin/.*)|
 (images/ads/.*)|
 (images/ext/.*)|
 (wsgiref/.*)|
 (doc/.*)|
 (profiling/.*)|
 (vendor/.*)
 )$
 
default_expiration: '365d'

handlers:
- url: /favicon.ico
  static_files: portfolios/media/images/favicon.ico
  upload: portfolios/media/images/favicon.ico
  mime_type: image/x-icon

- url: /.*
  script: thumbnail-service.py